version: "3.8"

volumes:
  sqlserver_vol:

networks:
  main:

services:
  #=============================================
  # SQL Server
  #=============================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    expose:
      - "1433"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "sqlserver_vol:/var/opt/mssql"
      - "./sqlserver/build:/docker-entrypoint-initdb.d"
    command:
      bash -c "chmod +x /docker-entrypoint-initdb.d/entrypoint.sh && /docker-entrypoint-initdb.d/entrypoint.sh ${DATABASE_PASSWORD}"
    networks:
      main:
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${DATABASE_PASSWORD}", "-Q", "select 1"]
      interval: "10s"
      retries: "10"
  #=============================================
  # Lucee BaseDao test service
  #=============================================
  lucee:
    image: ortussolutions/commandbox:lucee-light-alpine-3.4.0
    env_file: .env
    volumes:
      - "./lucee:/app"
    networks:
      main:
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    restart: always
